###
GET http://localhost:8888/agent/response HTTP/1.1
Content-Type: application/json

{
  "vectorStoreId": "vs_67d594a375c48191acb41791a0cc039f",
  "input": "A quins paisos funciona?"
}

###
GET http://localhost:8888/agent/dataset/setup HTTP/1.1
Content-Type: application/json